### ISSUE TITLE
Installer not compatible with Windows dark mode

### ISSUE THREAD

**Issue by ReenigneArcher** [msys2/msys2-installer#88] opened 2024-12-07 19:02 UTC
Cannot read text when dark mode is set in Windows settings.

Dark mode:
![image](https://github.com/user-attachments/assets/e270fdce-4766-40fe-8067-afa286caa27f)

Light mode:
![image](https://github.com/user-attachments/assets/ec5063e6-5078-4e61-b593-f04a0c8d6bfe)

**Comment by Biswa96** [comment] 2024-12-07 19:19
* Duplicate of #84

**Closed** 2024-12-07 19:42 UTC
