### ISSUE TITLE
Docker build hangs indefinitely after installing MSYS2

### ISSUE THREAD

**Issue by relapids** [msys2/msys2-installer#59] opened 2022-12-17 17:48 UTC
Related (?) issue: https://github.com/msys2/msys2-installer/issues/58

Thought I had the same issue but it turns out apparently not... Copying my message from there here below.

==========================

Same thing started happening to me yesterday with no changes on my end (been working for months up until now). Was definitely working two days ago since I have a script to force-rebuild my image daily. I see this on multiple machines and OS versions.

Tried both isolation modes (hyperv and process) and neither are currently working for me. One slight difference to the original reporter is that I'm using servercore:ltsc2022.

Still trying to diagnose further but unfortunately it's difficult to get diagnostic information from Windows containers for these sorts of issues. Trying to investigate using the information here: https://learn.microsoft.com/en-us/virtualization/windowscontainers/troubleshooting

EDIT:

Actually, I think I may have misunderstood the original issue in this thread and conflated it with mine. In my case the processes all appear to run successfully and terminate normally, but then the RUN step never finishes and just hangs indefinitely when finalizing the layer. I'm guessing this is probably a distinct issue and I misclassified it as the same as the one here due to the timing.

Strange though that it's happening on multiple machines and seems to coincide with the latest installer release. I tried rolling back to an earlier installer but that didn't help. Likely because whatever is causing the issue gets updated to the same version as in the latest installer anyway, but that's just a guess on my part so far - I need to do additional testing.

**Comment by lazka** [comment] 2022-12-17 17:49
thanks

**Comment by lazka** [comment] 2022-12-17 18:05
Thanks for testing, yeah, looks like the latest update broke something only in docker, which is why CI didn't catch it :(

**Comment by lazka** [comment] 2022-12-17 22:04
Please try again now

**Comment by lazka** [comment] 2022-12-18 09:24
> @lazka Wow that was fast. It appears to be working now. Thank you!

Thanks for testing.

> Out of curiosity, what did you change?

I wrote up my findings here: https://cygwin.com/pipermail/cygwin/2022-December/252711.html

**Comment by Biswa96** [comment] 2022-12-19 05:38
Can you get the version of msys2-runtime package - which one fails and which one does not ?

**Comment by lazka** [comment] 2022-12-21 08:40
I see, yeah these might be two unrelated issues. The ASLR change made our nightly builds fail which in turn meant installing the latest build and updating resulted in a runtime update.

**Comment by lazka** [comment] 2023-01-26 08:15
No update, but I can at least confirm the issue is reproducible in CI (this case installed a version leading to an update): https://github.com/msys2/msys2-installer/actions/runs/3953154465

**Comment by chadlwilson** [comment] 2023-12-01 09:00
Did anyone get any further on this one? Spent a few days hitting my head against a stuck Docker build after adding a `choco install msys2` and delighted to finally find this ticket so I can regain my sanity :-)

Running without doing the msys2 system update via either the choco package or ridk allows me to get a built container at least.

```powershell
cinst ruby                        # install ruby
cinst msys2 --params "/NoUpdate"  # install msys2 without system update
Update-SessionEnvironment         # refresh environment vars
ridk install 3
```

There is still an unexplained 10 minute delay building the layer from docker which is probably an unrelated or semi-related Docker on Windows file-system issue, but at least it doesn't seem indefinitely stuck.

```
Fri, 01 Dec 2023 07:44:06 GMT Completed provisioning.
Fri, 01 Dec 2023 07:54:07 GMT Removing intermediate container f1ab44003c4e
Fri, 01 Dec 2023 07:54:07 GMT  ---> 626dbeeb7fee
```

I've haven't yet tried excluding certain packages from the update to see if there are the same `msys2-runtime` culprits as above, but will try that next. Something in the below is probably the issue.

```
> sh -lc true
MSYS2 seems to be properly installed
Check msys2-keyring version:
 -> up-to-date
Remove catgets to avoid conflicts while update  ...
> pacman -Rdd catgets libcatgets --noconfirm
error: target not found: catgets
error: target not found: libcatgets
MSYS2 system update (optional) part 1  ...
> pacman -Syu --needed --noconfirm
:: Synchronizing package databases...
 clangarm64 downloading...
 mingw32 downloading...
 mingw64 downloading...
 ucrt64 downloading...
 clang32 downloading...
 clang64 downloading...
 msys downloading...
:: Starting core system upgrade...
resolving dependencies...
warning: terminate other MSYS2 programs before proceeding
looking for conflicting packages...

Packages (3) bash-5.2.021-1  mintty-1~3.7.0-1  msys2-runtime-3.4.9-3

Total Download Size:    4.98 MiB
Total Installed Size:  20.03 MiB
Net Upgrade Size:       0.06 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 bash-5.2.021-1-x86_64 downloading...
 libgettextpo-0.22.4-1-x86_64 downloading...
 libksba-1.6.5-1-x86_64 downloading...
 liblzma-5.4.5-1-x86_64 downloading...
 libnghttp2-1.58.0-1-x86_64 downloading...
 libintl-0.22.4-1-x86_64 downloading...
 libasprintf-0.22.4-1-x86_64 downloading...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
upgrading libintl...
upgrading libreadline...
upgrading gawk...
upgrading libgettextpo...
upgrading libasprintf...
upgrading gettext...
upgrading libgcrypt...
upgrading libp11-kit...
upgrading libgnutls...
upgrading libksba...
upgrading libsqlite...
upgrading libnghttp2...
upgrading p11-kit...
upgrading liblzma...
upgrading libxml2...
upgrading libxslt...
upgrading libgpgme...
upgrading xz...
:: Running post-transaction hooks...
(1/1) Updating the info directory file...
MSYS2 system update (optional) succeeded
```

**Comment by chadlwilson** [comment] 2024-02-24 14:27
There seems to be some discussion of similar Pacman hangs at https://github.com/git-for-windows/git-for-windows-automation/pull/61 but no idea if it’s related to the issue here, or just sounds similar.

**Comment by jeremyd2019** [comment] 2024-05-27 22:19
I played around with this by copying the docker bits from the CI from this repository, and I saw that the process moved on from the core update, but then experienced a hang after everything was updated.  I found that adding `rm -r -fo 'C:\$Recycle.Bin\';` to the end of the powershell command in the Dockerfile (after the `pacman -Scc`) seemed to allow the `docker build` to progress.  (I also added an `echo Done;` to the end to know that the powershell was completely over and I was probably waiting for Docker)

https://github.com/msys2/msys2-installer/blob/477a2f56032c967e67dbc3e9f043d0399ffa99b0/.ci/Dockerfile.2022#L11-L13

I'm guessing that docker is choking on the odd unicode characters in the 'binned' files?  msys2/MSYS2-packages#4622

Another thing I tried was adding msys2 `ps -e` and `Get-Process` to see if any background processes might be hanging around.  There were not.

**Comment by chadlwilson** [comment] 2024-05-28 01:37
Wow, thanks @jeremyd2019 - I'll try your workaround.

Does one perhaps conclude that docker build on windows tries to empty the recycle bin itself (perhaps for each layer) prior to completing and gets stuck?

**Comment by jeremyd2019** [comment] 2024-05-28 01:44
I was guessing that whatever docker uses to save the filesystem was tripping up on what are probably invalid unicode sequences.  But I don't know anything about what docker does.

**Comment by chadlwilson** [comment] 2024-05-28 01:46
Yeah that makes more sense given the nature of filesystems and what must be needed for layer exports on windows.

**Comment by jeremyd2019** [comment] 2024-05-28 01:51
If you're interested, the construction of the filenames is explained here: https://github.com/msys2/msys2-runtime/blob/abcb3c6c0f330ac7568956b2be6bf3376517bb56/winsup/cygwin/syscalls.cc#L342-L346

**Comment by chadlwilson** [comment] 2024-05-30 04:10
Your `rm -rf` workaround seemed to work just fine to resolve this problem within a `docker build`, allowing `msys2-runtime` and `pacman` to be updated during the container build. Thanks!

https://github.com/gocd-contrib/gocd-oss-cookbooks/compare/v3.16.4...v3.16.5

**Comment by chadlwilson** [comment] 2024-05-31 06:25
Ok, managed to find what seems the root problem here, with similar workarounds discovered: https://github.com/microsoft/Windows-Containers/issues/213

Fix appears to require a containerd (and presumably Docker runtime?) built with Go 1.21+ https://github.com/containerd/containerd/pull/8957#issuecomment-1694549913

I am currently using Windows Server 2022 images on GHA which at time of writing have Docker 24.0.7 on them. https://github.com/actions/runner-images/blob/releases/win22/20240514/images/windows/Windows2022-Readme.md

This has containerd 1.7.6 in it.

I believe the fix is only in containerd 1.7.14  which landed via https://github.com/containerd/containerd/pull/9860 and https://github.com/containerd/containerd/releases/tag/v1.7.14

I'm not sure if any released Docker engine version has that containerd version in it yet.

**Comment by chadlwilson** [comment] 2024-07-24 15:37
> I am currently using Windows Server 2022 images on GHA which at time of writing have Docker 24.0.7 on them. https://github.com/actions/runner-images/blob/releases/win22/20240514/images/windows/Windows2022-Readme.md This has containerd 1.7.6 in it; but in any case, both Go 1.20 built.

FWIW I re-tested this today without the "recycle bin removal workaround" on newer runner images that container Docker Engine `26.1.3` (containerd `1.7.15` static binaries) and **the issue is fixed**. This was with runner image [20240721.1](https://github.com/actions/runner-images/blob/win22/20240721.1/images/windows/Windows2022-Readme.md).

@jeremyd2019 IMHO I think this can probably be closed now, in that the root cause was containerd-on-Windows problems, for which it has been fixed upstream. If the "junk left in recycle bin" is a problem on its own, I imagine that can/should be addressed separately within msys2 somewhere?

**Comment by jeremyd2019** [comment] 2024-07-24 18:30
That's good.  I don't seem to have the ability to close this issue though

**Closed** 2024-07-24 18:33 UTC
